[2025-07-30T17:10:57.039+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T17:10:57.092+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T17:10:57.107+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T17:10:57.109+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-30T17:10:57.129+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-29 00:00:00+00:00
[2025-07-30T17:10:57.144+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2025-07-30T17:10:57.152+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_etl_dag', 'load_data', 'scheduled__2025-07-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_dags.py', '--cfg-path', '/tmp/tmp57clw523']
[2025-07-30T17:10:57.156+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data
[2025-07-30T17:10:57.193+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-30T17:10:57.289+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-29T00:00:00+00:00 [running]> on host 86109165cffe
[2025-07-30T17:10:57.463+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Luis' AIRFLOW_CTX_DAG_ID='pokemon_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-29T00:00:00+00:00'
[2025-07-30T17:10:57.465+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T17:10:57.598+0000] {load.py:39} INFO - Datos de Pokémon leídos exitosamente desde Parquet.
[2025-07-30T17:10:57.600+0000] {load.py:19} INFO - Intentando conectar a la base de datos PostgreSQL...
[2025-07-30T17:10:57.652+0000] {load.py:25} INFO - Conexión exitosa a la base de datos PostgreSQL.
[2025-07-30T17:10:57.808+0000] {load.py:62} INFO - Datos de Pokémon cargados exitosamente en la base de datos.
[2025-07-30T17:10:57.809+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-30T17:10:57.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T17:10:57.833+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=pokemon_etl_dag, task_id=load_data, execution_date=20250729T000000, start_date=20250730T171057, end_date=20250730T171057
[2025-07-30T17:10:57.889+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-30T17:10:57.926+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T17:10:57.929+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
